### ISSUE TITLE
Sorry to disturb you

### ISSUE THREAD

**Issue by xtvjxk123456** [Draketuroth/Maya-Custom-Viewport-Renderer#1]
I want to try your code，but I have no idea how to make it work.
I have completed the compilation
please show me the next.

**Comment by tntmeijs** [comment]
Hi there, @xtvjxk123456 . I have been playing around with this project because I am working on similar things myself. I managed to get it to work.

I know it's been a while since you've asked this question, but I might as well answer it for future reference... Please note that I am not the developer of this project.

1. Download / clone the repository.
2. Either download the required SDK, or retarget the projects.
3. Build all projects. (make sure to link to the Maya include and lib folders).
4. Find the `.mll` file that has been generated.
5. Move the `.mll` file to the folder that you set as the Maya plug-in folder (check the [documentation](https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2018/ENU/Maya-EnvVar/files/GUID-8EFB1AC1-ED7D-4099-9EEE-624097872C04-htm.html) for more information on configuring this)
6. Locate the Vanilla engine .exe file. (`Maya-Custom-Viewport-Renderer-master\x64\Debug\Vanilla_Engine.exe`)
7. Copy the "Textures" and "Shaders" folders to the same folder as the executable.
![image](https://user-images.githubusercontent.com/15856620/49433374-2dd56800-f7b2-11e8-987d-23724f967b78.png)
8. Run the Vanilla engine executable.
9. Open Maya and go to  `Windows > Settings/Preferences > Plug-in Manager`.
![image](https://user-images.githubusercontent.com/15856620/49433482-77be4e00-f7b2-11e8-8730-9b8c4be27ddc.png)
10. Load the plug-in called "Plugin.mll".
![image](https://user-images.githubusercontent.com/15856620/49433456-62492400-f7b2-11e8-95a8-2c29936ee991.png)
11. Add an object to the Maya scene, it should show up in the Vanilla engine window.
![image](https://user-images.githubusercontent.com/15856620/49433506-84db3d00-f7b2-11e8-8257-1d0b1c69188a.png)

**Comment by xtvjxk123456** [comment]
Thank you very much for your reply.
Have a nice day.

**Comment by Draketuroth** [comment]
Thank you for responding to this @tntmeijs, I realize I have not been around here in a long time. Sorry it took such a long time for me to respond. 👍 

@xtvjxk123456, I hope Tahar's guide worked for you, this is exactly what is necessary to do in order to get the application up and running at the moment. The reason for why it can be troublesome to use this project is that I haven't made any updates ever since I made the first initial commit about a year ago and the setup was following an internal standard I had established for just myself. While I do have plans on continuing my work someday, there are a lot of improvements to be made as you probably have noticed by now. It was a quick and "hackish" implementation over the period of a month, so a word of warning: don't rely too much on this example. If you have any questions (or feedback, always appreciated) about it though, feel free to send me an email on fredrik-linde@outlook.com. Same goes for you @tntmeijs :)
